### ISSUE TITLE
How to install on my own server?

### ISSUE THREAD

**Issue by seekr** [vinc/news.vinc.cc#51]
Hi Vinc, i discovered your news aggregator through hn and loved it for simplicity and how well it works for lower powered (and older) devices that struggle to run latest apps.

I don't know how to dev in Ruby but I can normally clone a node repo, run npm install and run a node app on a vps. I wonder if it would be as easy with a Ruby app (this app).

**Comment by vinc** [comment]
Hi @seekr, thanks! I wanted something that was simple, fast, and let me consume exactly the amount of news I want daily and weekly.

The app need Redis to cache the HTTP requests it's making to its news sources, and Mongo to store the user data encrypted on the client side without knowing the key.

Those data are used for synchronization between devices, and as long as you don't create an account on the settings page the app will work without Mongo. Now that I think about it I should hide the settings link if Mongo is not installed! It also remains usable without enabling JavaScript.

Anyway, I'd recommend using something like Heroku or a similiar self-hosted PaaS like Dokku that I've been using for years: http://dokku.viewdocs.io/dokku/

In the latter case here's the setup I'm using:

    # Dokku setup
    dokku plugin:install https://github.com/dokku/dokku-redis.git redis
    dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo
    dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
    dokku config:set --global DOKKU_LETSENCRYPT_EMAIL=alice@example.com

    # App setup
    dokku apps:create news
    dokku domains:add news news.example.com
    dokku config:set news TWITTER_KEY=xxxxx
    dokku config:set news TWITTER_SECRET=xxxxx
    dokku config:set news NEWSAPI_KEY=xxxxx
    dokku letsencrypt news
    dokku redis:create news-redis
    dokku redis:link news-redis news
    dokku mongo:create news-database
    dokku mongo:link news-database news

And after that on the client side I deploy like this:

    git remote add dokku dokku@dokku.example.com:news
    git push dokku master

You can also try it first locally like so:

    bundle install
    rails server

The app hasn't been updated in a while because it's good as it is for me at the moment, but I've been using it daily since I wrote it and if someone else is using it I'll upgrade to the latest Rails and Bootstrap version.

Thank you for asking, I'll add that to the README that looks rather empty and not very welcoming at the moment!

**Comment by seekr** [comment]
Thank you vinc, I got this working locally and through heroku.

As I wrote before, I'm now using a limited mobile device, and I love that this news reader is so light and doesn't depend on any databases or javascript!

**Comment by seekr** [comment]
btw, How should I deal with Rehost_URL? Currently it sets to default: localhost:400

**Comment by vinc** [comment]
Oups I completely forgot about the image rehosting service! It's based on this https://github.com/vinc/rehost and turns out I never open sourced the tiny server that run the code! Will do that after work.

Right now it's a separate service using node, but I've done the same kind of thing in the past with ruby so it'd be better to integrate that directly inside this web app. I'll add this to my TODO list, it's not hard to do.

Sorry about that, this project really need a complete README!

**Comment by seekr** [comment]
Thank you vinc!
